### PR TITLE
Adapt Roles and Roles Bindings to use the general components approach and work with k8s API

### PR DESCRIPTION
**Pull request by Wawrzyn321**
**Description**

Changes proposed in this pull request:

- Add views for `roleBindings` and `clusterRoleBindings`
- I decided to keep an additional change - finding generic components by case-insensitive name

### CODE REVIEW

**Review by dariadomagala — COMMENTED** [review]
please remove old components

**Comment by Wawrzyn321** [comment]
bruh

**Review by dariadomagala — APPROVED** [review]
❤️ cleanups

**Pull request merged**
