### PR TITLE
Rename labels to metadata

### PR DESCRIPTION
**Pull request by parostatkiem**
**Description**
Rename "labels" to "metadata definitions" on lists, modals and panels
Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by Wawrzyn321** [comment]
image

**Comment by Wawrzyn321** [comment]
image
Let's stick to one case.

**Comment by Wawrzyn321** [comment]
image

**Comment by parostatkiem** [comment]
@Wawrzyn321 done

**Comment by Wawrzyn321** [comment]
One last thing - `CreateLabelModal.container.js` can be removed now.

**Pull request merged**
